import React, { Component } from "react";
import logo from "./logo.svg";
import "./App.css";

const musicData = [
  { id: 1,
  name: "Steven",
  band: "Daft punk",
  song: "Digital Love" },

  {
    id: 2,
    name: "Jason",
    band: "Radiohead",
    song: "These are my twisted words"
  },
  {
    id: 3,
    name: "Vicky",
    band: "Khruangbin",
    song: "White gloves"
  },
  {
    id: 4,
    name: "Gabby",
    band: "Billy Joel",
    song: "Vienna"
  },
  {
    id: 5,
    name: "Hamilton",
    band: "Fleetwood Mac",
    song: "Gold Dust Woman"
  },
  {
    id: 6,
    name: "Jacob",
    band: "Kanye West",
    song: "Goldigger"
  }
];

{
  /* EXAMPLE OF WHAT THE HTML GENERATED BY FavMusic SHOULD LOOK LIKE
    <div>
      <h2>Steven preferences: </h2>
      <p>
        Steven loves Daft punk and recommends <strong>Digital Love</strong>
      </p>
    </div>
    <div>
      <h2>Jason preferences: </h2>
      <p>
        Jason loves Radiohead and recommends{" "}
        <strong>These are my twisted words</strong>
      </p>
    </div>
    <div>
      <h2>Vickty preferences: </h2>
      <p>
        Vickty loves Khruangbin and recommends <strong>White gloves</strong>
      </p>
    </div>
  */
}

const FavMusic = props => {

  // your code goes here
  // this component should receive a prop with the music data
  console.log("The music data is :", props.musicData);
  return (
    musicData.map((data) =>
      <div key={data.id}>
        <h2>{data.name}'s preferences: </h2>
        <p>
          {data.name} loves {data.band} and recommends <strong>{data.song}</strong>
        </p>
      </div>
    )
  )
}

// class FavMusic extends Component {
//   render(){
//     console.log(this.props);
//     return (
//       this.props.musicData.map((data, id) =>
//         <div key={data.id}>
//           <h2>{data.name}'s preferences: </h2>
//           <p>
//             {data.name} loves {data.band} and recommends <strong>{data.song}</strong>
//           </p>
//         </div>
//       )
//     )
//   }
// }



const App = props => {
  return <FavMusic musicData={musicData}/>;
};

export default App;
